services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy  # The Docker image to use.
    container_name: wg-easy         # Name of the container.
    environment:                    # Environment variables to configure the instance.
      - LANG=en                     # Language settings.
      - WG_HOST=liourtas.ddns.net          # Public IP or domain name where WG-Easy is accessible.
      - PASSWORD_HASH=$$2y$$05$$gZWPNPoXsGD/atIxqD/OfekfspzA1MTQUPZOPHgXg1LgELw7relii # Bcrypt hash for Web UI login.
      - PORT=51821                  # Port for the web interface.
      - WG_PORT=51820               # WireGuard port for VPN traffic.
    volumes:
      - ./wg-easy/:/etc/wireguard   # Volume mapping for WireGuard configuration files.
    ports:
      - "51820:51820/udp"           # UDP port used by WireGuard.
      - "51821:51821/tcp"           # TCP port for accessing the web interface.
    cap_add:                        # Capabilities required for managing networking features.
      - NET_ADMIN
      - SYS_MODULE
    sysctls:                        # Kernel parameters that need to be set for WireGuard.
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    restart: unless-stopped         # Ensures the container restarts automatically unless manually stopped.
  ddns-updater:
    image: ghcr.io/noipcom/noip-duc:latest
    container_name: ddns-updater
    environment: 
      - NOIP_USERNAME=mq6yn7e
      - NOIP_PASSWORD=DwH9Hhopc2vG
      - NOIP_HOSTNAMES=group-liourtas
