#Hello World!!!
services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./vaultwarden/data:/data
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/caddy_data:/data
      - ./caddy/caddy_config:/config
      - ./caddy/certs:/certs
  dns:
    image: coredns/coredns:latest
    container_name: coredns
    restart: unless-stopped
    ports:
      - "53:53/udp"
    volumes:
      - ./dns/Corefile:/Corefile
  freshrss:
    image: freshrss/freshrss:latest
    container_name: freshrss
    restart: unless-stopped
    ports:
      - "8081:80"  # You can change 8080 to any port you want
    volumes:
      - ./freshrss/data:/var/www/FreshRSS/data
      - ./freshrss/extensions:/var/www/FreshRSS/extensions
    environment:
      - CRON_MIN=4,34  # Optional: update feeds every 30 minutes
      - TZ=Europe/Athens  # Set your local timezone
  netdata:
    image: netdata/netdata:stable
    container_name: netdata
    pid: host
    network_mode: host
    restart: unless-stopped
    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    volumes:
      - ./netdata/config/:/etc/netdata
      - ./netdata/netdatalib:/var/lib/netdata
      - ./netdata/netdatacache:/var/cache/netdata
      - /:/host/root:ro,rslave
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /etc/localtime:/etc/localtime:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
      - /var/log:/host/var/log:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /run/dbus:/run/dbus:ro
    environment:
      - NETDATA_CLAIM_TOKEN=Yif0EOapS15OZlyHA8uGP6gBGy_oSjQB1I2YYtc6VExWW52I-fbIk9ixpD5FtKg5oFllxbOOKs5Z7s2jwW07i7r7wYvIy8ix0FhuyTHwloNN_SdDH8Vnfa41L8-eyzoLvLPGwxU
      - NETDATA_CLAIM_URL=https://app.netdata.cloud
      - NETDATA_CLAIM_ROOMS=31c66b55-6ba0-4ec1-b103-4f3937d9a878
volumes:
  netdataconfig:
  netdatalib:
  netdatacache:

