- name: Update docker-compose file
  hosts: homelab
  tasks:
    - name: Ensure docker-compose file exists
      stat: 
        path: ~/selfhosted/docker-compose.yml
      register: docker_compose_file

    - name: Fail if docker-compose does not exist
      fail: 
        msg: "Docker Compose file does not exist at ~/selfhosted/"
      when: docker_compose_file.stat.exists == false
      
    - name: Append comment to docker-compose.yml
      lineinfile:
        path: ~/selfhosted/docker-compose.yml
        line: '# Hello World!'
        insertafter: EOF
      when: docker_compose_file.stat.exists
