name: Run Ansible Playbook on Push to Main

on:
  push:
    branches:
      - main

jobs:
  run-playbook:
    runs-on: ubuntu-latest  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up WireGuard connection
        uses: niklaskeerl/easy-wireguard-action@v2
        with:
          WG_CONFIG_FILE: ${{ secrets.WG_CONFIG_FILE }}

      - name: Test VPN connectivity to lope
        run: ping -c 3 192.168.2.20

      - name: Test VPN connectivity to berry
        run: ping -c 3 192.168.2.19

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa
          ssh-keyscan -H 192.168.2.19 >> ~/.ssh/known_hosts
          ssh-keyscan -H 192.168.2.20 >> ~/.ssh/known_hosts
 
      - name: Run the Ansible playbook
        run: |
          ansible-playbook -i homelab/ansible/inventory.ini homelab/ansible/playbook.yml
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"  # To avoid SSH key verification issues
