name: Copy new docker compose on lope

on:
  push:
    paths:
      - 'homelab/lope/managed/docker-compose.yml'
env:
  # Use the same ssh-agent socket value across all jobs
  SSH_AUTH_SOCK: /tmp/ssh_agent.sock
  lope_become_pass: ${{ secrets.LOPE_BECOME_PASS }}

jobs:
  run-playbook:
    runs-on: ubuntu-latest  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up WireGuard connection
        uses: niklaskeerl/easy-wireguard-action@v2
        with:
          WG_CONFIG_FILE: ${{ secrets.WG_CONFIG_FILE }}

      - name: Test VPN connectivity to lope
        run: ping -c 3 192.168.2.20

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Ansible and collections
        run: |
          python -m pip install --upgrade pip
          pip install ansible
          ansible-galaxy collection install -r homelab/ansible/requirements.yml

      - name: Set up SSH key with passphrase
        env:
          LOPE_SSH_PASSPHRASE: ${{secrets.LOPE_SSH_PASSPHRASE}}
          LOPE_SSH_PRIVATE_KEY: ${{secrets.LOPE_SSH_PRIVATE_KEY}}
        run: |
          # Start ssh-agent
          eval "$(ssh-agent -a $SSH_AUTH_SOCK)"
          #Create and chmod the askpass script
          echo "echo \$LOPE_SSH_PASSPHRASE" > ~/.askpass_lope && chmod +x ~/.askpass_lope
          #Add lope key
          echo "$LOPE_SSH_PRIVATE_KEY" | tr -d '\r' | DISPLAY=none SSH_ASKPASS=~/.askpass_lope ssh-add - 

      - name: Run the Ansible playbook
        run: |
          ansible-playbook -i homelab/ansible/inventory.ini homelab/ansible/lope-update-compose.yml -e "compose_file=$(pwd)/homelab/lope/managed/docker-compose.yml"
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"  # To avoid SSH key verification issues

